### ISSUE TITLE
Using My Own Songs

### ISSUE THREAD

**Issue by impulsecorp** [magenta/listen-to-transformer#2]
I was able to run Listen to Transformer on my own server to play your songs, but is there any way for me to use it to play a library of songs I generate myself using Magenta? I tried changing it to use my MIDI directory (full of songs I pre-generated) instead of yours, but that did not work.

**Comment by notwaldorf** [comment]
You have to also change how the random midi files are picked, [here](https://github.com/magenta/listen-to-transformer/blob/master/script.js#L360). I think that function, in combination with updating these variables to match your dataset should do:
```
const MODEL = 'a1';
const NUM_MODEL_FILES = 99975;
const FILE_PREFIX = 'https://magentadata.storage.googleapis.com/piano_transformer/midi/';
```

Let me know if this doesn't work for you and I can give it a try.

**Comment by impulsecorp** [comment]
Yes, that worked. Changing the getRandomMidiFilename code is what was needed. I know very little Java, so maybe I was missing something, but after many tries I could not still not get it to work like I thought it would, so I hard coded my File_Prefix URL into the  getRandomMidiFilename code and that made it work.  My variables were:
const MODEL = 'a1';
const NUM_MODEL_FILES = 100;
const FILE_PREFIX = '/home/bitnami/boredhumans.com/midi_player/midi/';

I named my 100 MIDI files 1.mid, 2.mid, 3.mid etc. and thought this would work as you had it:
return `${FILE_PREFIX}${MODEL}/${index}.mid`;
but the only way I could get it to work was removing "${MODEL}" and also using my website URL (the path did not work) instead of the FILE_PREFIX:
return `https://boredhumans.com/midi_player/midi/${index}.mid`;

It is not a problem for me to have it like that, I just wanted to give all the info in case anybody else is trying to do this also.

**Comment by notwaldorf** [comment]
yay, glad that worked!

**Comment by asigalov61** [comment]
Thanks for this solution. Very useful :) I have not checked it yet but I will and update :)
